---
abstract: 'Tokenize RTF'
author:
  - 'Peter Sergeant <pete@clueball.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RTF-Tokenizer
requires:
  ExtUtils::MakeMaker: '6.30'
  IO::Scalar: '0'
  perl: v5.6.2
version: '1.19'
